### PR TITLE
Production rebase from original

### PR DESCRIPTION
**Pull request by waynarbocangel**
Fixed issue with redirection to localhost causing the server to seem down.

### CODE REVIEW

**Review by forschoolandnothingelse — COMMENTED** [review]
I don't know what other errors could occur, but it seems like if any error occurs, not just an auth error, it will spit the user out at the `/login` route. Is this what we want to happen?

**Comment by waynarbocangel** [comment]
That's actually no the behavior. Right now the code will redirect to login if it cannot read a User object value from local storage. If for any reason this read fails we should redirect to login and create a new local instance that can be read properly by login in or creating a new user. In the case of any other errors the page would actually stay blank, which might also not be a behavior we want, but that is something we would have to address with a different issue entirely.

**Review by forschoolandnothingelse — APPROVED** [review]
Just wanted to clarify the intended behavior in case we encounter any other, unexpected errors.

**Review by ehsonp — APPROVED** [review]
I believe this should fix it but in the future would we change it back to something elese? like the production environment?

**Pull request merged**
